### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by olegsidokhmetov** [GabrielAgrela/OSROKBOT#21]
Nox - 1280*720

[{
	"resource": "/c:/Users/IAM/Downloads/OSROKBOT-master/Classes/UI.py",
	"owner": "cSpell",
	"severity": 2,
	"message": "\"ROKBOT\": Unknown word.",
	"source": "cSpell",
	"startLineNumber": 5,
	"startColumn": 9,
	"endLineNumber": 5,
	"endColumn": 15
},{
	"resource": "/c:/Users/IAM/Downloads/OSROKBOT-master/Classes/UI.py",
	"owner": "cSpell",
	"severity": 2,
	"message": "\"OSROKBOT\": Unknown word.",
	"source": "cSpell",
	"startLineNumber": 5,
	"startColumn": 23,
	"endLineNumber": 5,
	"endColumn": 31
},{
	"resource": "/c:/Users/IAM/Downloads/OSROKBOT-master/Classes/UI.py",
	"owner": "cSpell",
	"severity": 2,
	"message": "\"pygetwindow\": Unknown word.",
	"source": "cSpell",
	"startLineNumber": 6,
	"startColumn": 8,
	"endLineNumber": 6,
	"endColumn": 19
},{
	"resource": "/c:/Users/IAM/Downloads/OSROKBOT-master/Classes/UI.py",
	"owner": "cSpell",
	"severity": 2,
	"message": "\"ROKBOT\": Unknown word.",
	"source": "cSpell",
	"startLineNumber": 17,
	"startColumn": 17,
	"endLineNumber": 17,
	"endColumn": 23
},{
	"resource": "/c:/Users/IAM/Downloads/OSROKBOT-master/Classes/UI.py",
	"owner": "cSpell",
	"severity": 2,
	"message": "\"OSROKBOT\": Unknown word.",
	"source": "cSpell",
	"startLineNumber": 17,
	"startColumn": 26,
	"endLineNumber": 17,
	"endColumn": 34
},{
	"resource": "/c:/Users/IAM/Downloads/OSROKBOT-master/Classes/UI.py",
	"owner": "cSpell",
	"severity": 2,
	"message": "\"ROKBOT\": Unknown word.",
	"source": "cSpell",
	"startLineNumber": 18,
	"startColumn": 17,
	"endLineNumber": 18,
	"endColumn": 23
},{
	"resource": "/c:/Users/IAM/Downloads/OSROKBOT-master/Classes/UI.py",
	"owner": "cSpell",
	"severity": 2,
	"message": "\"ROKBOT\": Unknown word.",
	"source": "cSpell",
	"startLineNumber": 19,
	"startColumn": 42,
	"endLineNumber": 19,
	"endColumn": 48
},{
	"resource": "/c:/Users/IAM/Downloads/OSROKBOT-master/Classes/UI.py",
	"owner": "cSpell",
	"severity": 2,
	"message": "\"ROKBOT\": Unknown word.",
	"source": "cSpell",
	"startLineNumber": 19,
	"startColumn": 57,
	"endLineNumber": 19,
	"endColumn": 63
},{
	"resource": "/c:/Users/IAM/Downloads/OSROKBOT-master/Classes/UI.py",
	"owner": "cSpell",
	"severity": 2,
	"message": "\"OSROKBOT\": Unknown word.",
	"source": "cSpell",
	"startLineNumber": 93,
	"startColumn": 46,
	"endLineNumber": 93,
	"endColumn": 54
},{
	"resource": "/c:/Users/IAM/Downloads/OSROKBOT-master/Classes/UI.py",
	"owner": "cSpell",
	"severity": 2,
	"message": "\"Frameless\": Unknown word.",
	"source": "cSpell",
	"startLineNumber": 251,
	"startColumn": 39,
	"endLineNumber": 251,
	"endColumn": 48
},{
	"resource": "/c:/Users/IAM/Downloads/OSROKBOT-master/Classes/UI.py",
	"owner": "cSpell",
	"severity": 2,
	"message": "\"OSROKBOT\": Unknown word.",
	"source": "cSpell",
	"startLineNumber": 252,
	"startColumn": 30,
	"endLineNumber": 252,
	"endColumn": 38
},{
	"resource": "/c:/Users/IAM/Downloads/OSROKBOT-master/Classes/UI.py",
	"owner": "cSpell",
	"severity": 2,
	"message": "\"backgourd\": Unknown word.",
	"source": "cSpell",
	"startLineNumber": 261,
	"startColumn": 22,
	"endLineNumber": 261,
	"endColumn": 31
},{
	"resource": "/c:/Users/IAM/Downloads/OSROKBOT-master/Classes/UI.py",
	"owner": "cSpell",
	"severity": 2,
	"message": "\"OSROKBOT\": Unknown word.",
	"source": "cSpell",
	"startLineNumber": 268,
	"startColumn": 42,
	"endLineNumber": 268,
	"endColumn": 50
}]

Your UI Instance
No window found with title: Rise of Kingdoms
Exception in thread Thread-2 (run_single_machine):
Traceback (most recent call last):
  File "C:\Users\IAM\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1052, in _bootstrap_inner
    self.run()
  File "C:\Users\IAM\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 989, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\IAM\Downloads\OSROKBOT-master\Classes\OS_ROKBOT.py", line 29, in run_single_machine
    if machine.execute():
       ^^^^^^^^^^^^^^^^^
  File "c:\Users\IAM\Downloads\OSROKBOT-master\Classes\state_machine.py", line 20, in execute
    result = state.perform()
             ^^^^^^^^^^^^^^^
  File "c:\Users\IAM\Downloads\OSROKBOT-master\Classes\Actions\action.py", line 38, in perform
    result = self.execute()
             ^^^^^^^^^^^^^^
  File "c:\Users\IAM\Downloads\OSROKBOT-master\Classes\Actions\screenshot_action.py", line 23, in execute
    width, height = screenshot.size
                    ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'size'
No window found with title: Rise of Kingdoms
Exception in thread Thread-5 (run_single_machine):
Traceback (most recent call last):
  File "C:\Users\IAM\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1052, in _bootstrap_inner
    self.run()
  File "C:\Users\IAM\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 989, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\IAM\Downloads\OSROKBOT-master\Classes\OS_ROKBOT.py", line 29, in run_single_machine
    if machine.execute():
       ^^^^^^^^^^^^^^^^^
  File "c:\Users\IAM\Downloads\OSROKBOT-master\Classes\state_machine.py", line 20, in execute
    result = state.perform()
             ^^^^^^^^^^^^^^^
  File "c:\Users\IAM\Downloads\OSROKBOT-master\Classes\Actions\action.py", line 38, in perform
    result = self.execute()
             ^^^^^^^^^^^^^^
  File "c:\Users\IAM\Downloads\OSROKBOT-master\Classes\Actions\screenshot_action.py", line 23, in execute
    width, height = screenshot.size

**Comment by Smokez01** [comment]
Is there a question?
