### ISSUE TITLE
ChatGPT error. 

### ISSUE THREAD

**Issue by wgiles200** [GabrielAgrela/OSROKBOT#23]
I put my key into the .env file but receiving this error message? Everything else is working fine. 

Exception in thread Thread-57 (run_single_machine):
Traceback (most recent call last):
  File "C:\Users\icema\anaconda3\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\icema\anaconda3\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\icema\Desktop\OSROKBOT-master\Classes\OS_ROKBOT.py", line 29, in run_single_machine
    if machine.execute():
       ^^^^^^^^^^^^^^^^^
  File "C:\Users\icema\Desktop\OSROKBOT-master\Classes\state_machine.py", line 20, in execute
    result = state.perform()
             ^^^^^^^^^^^^^^^
  File "C:\Users\icema\Desktop\OSROKBOT-master\Classes\Actions\action.py", line 38, in perform
    result = self.execute()
             ^^^^^^^^^^^^^^
  File "C:\Users\icema\Desktop\OSROKBOT-master\Classes\Actions\chatgpt_action.py", line 62, in execute
    chat = openai.chat.completions.create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\icema\anaconda3\Lib\site-packages\openai\_utils\_utils.py", line 275, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\icema\anaconda3\Lib\site-packages\openai\resources\chat\completions.py", line 667, in create
    return self._post(
           ^^^^^^^^^^^
  File "C:\Users\icema\anaconda3\Lib\site-packages\openai\_base_client.py", line 1213, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\icema\anaconda3\Lib\site-packages\openai\_base_client.py", line 902, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\Users\icema\anaconda3\Lib\site-packages\openai\_base_client.py", line 993, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'message': 'The model `gpt-4-1106-preview` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}

Press k to for the next question

**Comment by roniez** [comment]
This is because the model gpt-4-1106-preview is not available any longer. 
I am working on solving this one in my fork but since I cannot solve the other issue I have not uploaded that fix yet and not requested a pull request.
