### ISSUE TITLE
 error: subprocess-exited-with-error

### ISSUE THREAD

**Issue by olegsidokhmetov** [GabrielAgrela/OSROKBOT#34]
Hi,

I got an error, when using pip install -r requirements.txt

PS D:\Games\OSROKBOT-master> `pip install -r requirements.txt`
Collecting keyboard==0.13.5 (from -r requirements.txt (line 1))
  Using cached keyboard-0.13.5-py3-none-any.whl.metadata (4.0 kB)
Collecting mss==9.0.1 (from -r requirements.txt (line 2))
  Using cached mss-9.0.1-py3-none-any.whl.metadata (3.9 kB)
Collecting numpy==1.26.2 (from -r requirements.txt (line 3))
  Using cached numpy-1.26.2.tar.gz (15.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting openai==1.6.1 (from -r requirements.txt (line 4))
  Using cached openai-1.6.1-py3-none-any.whl.metadata (17 kB)
Collecting Pillow==10.1.0 (from -r requirements.txt (line 5))
  Using cached Pillow-10.1.0.tar.gz (50.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  ```
× Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel   
          return hook(config_settings)
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-knm4du12\overlay\Lib\site-packages\setuptools\build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-knm4du12\overlay\Lib\site-packages\setuptools\build_meta.py", line 304, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-knm4du12\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 30, in <module>
        File "<string>", line 27, in get_version
      KeyError: '__version__'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

note: This error originates from a subprocess, and is likely not a problem with pip.

P.S. Why in requirements.txt 2 lines
```
Pillow==10.1.0
Pillow==10.1.0
```
Is this correct?

**Comment by olegsidokhmetov** [comment]
By the time support arrives, I've already solved the problem myself.
